### ISSUE TITLE
Is the code ready to run?

### ISSUE THREAD

**Issue by Beniko95J** [AutoAILab/DynamicDepth#1]
Hi, thank you for open-sourcing your great work!

I find that there are still some mistaken imports left in the code and I cannot find the masks that you used to disentangle the dynamic objects. Will the code be ready to run soon?

**Comment by Magicboomliu** [comment]
Same Concerns as @Beniko95J 

Looking forward to more details.

**Comment by JunjieLiuSWU** [comment]
Do you mean "aug_mask" in the inference phase?

**Comment by Magicboomliu** [comment]
您好，邮件已收到。感谢来信 ，我会尽快回复您。  Hello, I have already received the letter. Thanks for your mailing, I will reply as soon as possible.  こんにちは！確かご電子メールをもらいました。私はできるだけ早くあなたに返事を出します。

**Comment by Beniko95J** [comment]
I mean the ``doj_mask``, ``doj_mask-1`` and ``doj_mask+1`` used during training.

**Comment by fengziyue** [comment]
Hi:

Appreciate your interest in our work! I'm still preparing the code, it will be released in several days.

Thank you!

**Comment by Beniko95J** [comment]
It seems that the documentation and codes are updated. Reopen this issue if necessary.
