### ISSUE TITLE
Is the Occlusion-aware Cost Volume rely on the outputs of the teacher model?

### ISSUE THREAD

**Issue by Ecalpal** [AutoAILab/DynamicDepth#10]
Thanks for your interesting job !  @fengziyue 

I think your work is very enlightening for researchers of monocular depth estimation.

What I want to know is,
does the occlusion-aware cost volume rely on the outputs of the teacher model? (see [here](https://github.com/AutoAILab/DynamicDepth/blob/309a57fe261fcd43f2b53989341948e1bec79ec8/dynamicdepth/trainer.py#L399))

It seems that we must use the depth from the teacher model to warp the target frame to get the new lookup_frames. Thus we must include the teacher model at the inference time.

Have I understood correctly?

**Comment by fengziyue** [comment]
Hi @Ecalpal :

Thank you for your interest! That's correct, the 'teacher model' in the code is the 'depth prior model' in our paper, which is needed for the inference.

**Comment by Ecalpal** [comment]
Thanks for your answer!
