### ISSUE TITLE
About intrinsics

### ISSUE THREAD

**Issue by JunjieLiuSWU** [AutoAILab/DynamicDepth#4]
The intrinsics is directly written in kitty_dataset.py, but as far as I know, the calibration metrics may be different between sequeces, so how is the intrinsics in the code come from?

**Comment by fengziyue** [comment]
Following the convention of Monodepth2 and Manydepth, since the difference of intrinsics in the KITTI dataset is minor, we use one universal intrinsic for the entire KITTI dataset.
