### ISSUE TITLE
Download failing for dynamic object mask on Cityscapes dataset

### ISSUE THREAD

**Issue by Handy-lineS** [AutoAILab/DynamicDepth#5]
Hi, I tried to download dynamic object masks, but it keeps failing.

Can you please check the occurring error?

Thank you

**Comment by fengziyue** [comment]
Hi

that link works good on my end, do you have any trouble accessing the google drive?

**Comment by Handy-lineS** [comment]
The link works fine but it keeps failing when it reaches 30GB/43G

**Comment by fengziyue** [comment]
I will try to upload it to OneDrive

**Comment by fengziyue** [comment]
Hi @Handy-lineS 

Appreciate your interest in our work, you can try to download from below OneDrive link:
https://clemson-my.sharepoint.com/:u:/g/personal/zfeng_clemson_edu/ETJLmJVJz4FBoBLMxJ53T5wB_uGpCqtr9TktJTKgYdgbHA?e=I1fbWC

**Comment by Handy-lineS** [comment]
Thank you, it has been solved!

**Comment by yzfzzz** [comment]
The Onedrive link is out of date, could you please provide another one (because google drive often fails to download)

**Comment by fengziyue** [comment]
> The Onedrive link is out of date, could you please provide another one (because google drive often fails to download)

Hi:

Thank you for your interest, I have updated the link.

**Comment by water-melon6086** [comment]
@fengziyue Hello!I'm really sorry to bother you. I can't download the dynamic object masks for the Cityscapes dataset from the provided Google Drive or OneDrive. It seems that the link has expired. Could you help me solve this problem?

**Comment by fengziyue** [comment]
Hi @water-melon6086 
Apologize for the delay, does this link work at your end?
https://drive.google.com/drive/folders/1GqDVWIIpK02rBPILDn1UmwlfFjGJyRrE?usp=sharing

**Comment by water-melon6086** [comment]
@fengziyue Thank you very much for your reply. The problem has been solved. I'm sorry for replying to you so late.
